wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.13
    start_time: 1630082144
    t:
      1:
      - 3
      - 12
      4: 3.6.13
      5: 0.12.1
      8:
      - 5
