wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.9
    start_time: 1630581596
    t:
      1:
      - 2
      - 3
      - 12
      2:
      - 2
      - 3
      - 12
      3:
      - 2
      4: 3.6.9
      5: 0.12.1
      8:
      - 5
agent:
  desc: null
  value: dqn
environment:
  desc: null
  value: cartpole
normalization:
  desc: null
  value: non_normalization
random seed:
  desc: null
  value: 1
varying:
  desc: null
  value: normalization
